###
# Start with: docker-compose -f misc/docker/stack.yml up -d
###

###
# Stop with: docker-compose -f misc/docker/stack.yml down
###

###
# Delete with: docker-compose -f misc/docker/stack.yml rm
###

version: '3.1'

services:
  zk1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

  zk2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zk3:2888:3888

  zk3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=0.0.0.0:2888:3888

  bboxdb1:
    image: jnidzwetzki/bboxdb:latest
    restart: always
    hostname: bboxdb1
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - 10081:10085
      - 50501:50505
    environment:
      ZK_HOSTS: zk1, zk2, zk3

  bboxdb2:
    image: jnidzwetzki/bboxdb:latest
    restart: always
    hostname: bboxdb2
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - 10082:10085
      - 50502:50505
    environment:
      ZK_HOSTS: zk1, zk2, zk3

  bboxdb3:
    image: jnidzwetzki/bboxdb:latest
    restart: always
    hostname: bboxdb3
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - 10083:10085
      - 50503:50505
    environment:
      ZK_HOSTS: zk1, zk2, zk3

  bboxdb4:
    image: jnidzwetzki/bboxdb:latest
    restart: always
    hostname: bboxdb4
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - 10084:10085
      - 50504:50505
    environment:
      ZK_HOSTS: zk1, zk2, zk3

  bboxdb5:
    image: jnidzwetzki/bboxdb:latest
    restart: always
    hostname: bboxdb5
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - 10085:10085
      - 50505:50505
    environment:
      ZK_HOSTS: zk1, zk2, zk3