title: 'BBoxDB'
subtitle: '- The database for multidimensional big data'

navigation: 2

permalink: none

codeurl: 'https://github.com/jnidzwetzki/bboxdb'

baseurl: 'http://jnidzwetzki.github.io/bboxdb/'

sections: [
    ['doc', 'Documentation'],
    ['examples', 'Examples'],
    ['tools', 'Tools'],
    ['dev', 'Developer'],
]
